# Generated by Django 6.0.2 on 2026-04-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=12),
            preserve_default=False,
        ),
    ]
